CREATE OR REPLACE PACKAGE BODY SYS.UTL_MAIL_INTERNAL IS
  
    PROCEDURE GET_SMTP_SERVER(SMTP_SERVER OUT VARCHAR2) IS
    BEGIN
      SELECT RTRIM(VALUE) INTO SMTP_SERVER 
      FROM V$PARAMETER
      WHERE UPPER(NAME)='SMTP_OUT_SERVER';
  
      
      IF (SMTP_SERVER = '') THEN
        SELECT VALUE INTO SMTP_SERVER 
        FROM V$PARAMETER 
        WHERE UPPER(NAME) = 'DB_DOMAIN';
      END IF;
    END;
  
  END;
/
